name: Deploy tlm-zprime-stg

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read # This is required for actions/checkout@v2

jobs:
  build:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1  

    # We can add more Node versions to the array if needed.
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v2

      # Sets up the Node.js environment.
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Npm Clean Install
        run: |
          npm ci
      - name: Production Build
        run: |
          npm run build
        env: 
          CI: ""

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume:  ${{ secrets.AWS_STAGING_ROLE }}
          role-session-name: rolesession
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Deploy
        run: |
          aws s3 sync build/ ${{ secrets.AWS_STAGING_BUCKET_NAME }}
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_STAGING_DISTRIBUTION }} --paths "/*"
